In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import os
from src.data_ingestion import (
    load_static_data,
    validate_columns,
    preprocess_sensor_data,
    data_quality_checks,
)
from src.operational_efficiency import (
    estimate_operational_efficiency,
    calculate_specific_power_windows,
)

In [3]:
COMPRESSOR_SPECS, DATA_SPECIFICATION = load_static_data()

raw_df = pd.read_csv("data/station_sensor_data.csv")
missing_cols = validate_columns(raw_df, DATA_SPECIFICATION["column_name"])
processed_df = preprocess_sensor_data(raw_df, DATA_SPECIFICATION)
df = processed_df.copy()

In [ ]:
df

,compressor_1_pressure,compressor_1_flow,compressor_1_power,compressor_1_activity,compressor_1_oil_temp,compressor_1_availability,compressor_2_pressure,compressor_2_flow,compressor_2_power,compressor_2_activity,...,compressor_4_flow,compressor_4_power,compressor_4_activity,compressor_4_bov_position,compressor_4_oil_temp,compressor_4_availability,station_pressure,station_flow,station_power,station_specific_power
timestamp,,,,,,,,,,,,,,,,,,,,,
2024-01-15 00:00:00,96.07,0.0,0.0,off,30.0,available,96.07,0.0,0.0,off,...,0.0,0.0,off,0.0,30.0,available,96.07,119.4,37.56,0.3146
2024-01-15 00:01:00,96.27,0.0,0.0,off,30.0,available,96.27,0.0,0.0,off,...,0.0,0.0,off,0.0,30.0,available,96.27,113.4,34.19,0.3015
2024-01-15 00:02:00,96.66,0.0,0.0,off,30.0,available,96.66,0.0,0.0,off,...,0.0,0.0,off,0.0,30.0,available,96.66,102.1,34.82,0.3410
2024-01-15 00:03:00,96.13,0.0,0.0,off,30.0,available,96.13,0.0,0.0,off,...,0.0,0.0,off,0.0,30.0,available,96.13,110.6,34.54,0.3123
2024-01-15 00:04:00,95.73,0.0,0.0,off,30.0,available,95.73,0.0,0.0,off,...,0.0,0.0,off,0.0,30.0,available,95.73,117.3,36.86,0.3142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-21 23:55:00,96.74,0.0,0.0,off,30.0,available,96.74,0.0,0.0,off,...,0.0,0.0,off,0.0,30.0,available,96.74,120.9,37.33,0.3088
2024-01-21 23:56:00,95.83,0.0,0.0,off,30.0,available,95.83,0.0,0.0,off,...,0.0,0.0,off,0.0,30.0,available,95.83,131.1,42.80,0.3265
2024-01-21 23:57:00,95.24,0.0,0.0,off,30.0,available,95.24,0.0,0.0,off,...,0.0,0.0,off,0.0,30.0,available,95.24,94.8,33.54,0.3538
2024-01-21 23:58:00,96.78,0.0,0.0,off,30.0,available,96.78,0.0,0.0,off,...,0.0,0.0,off,0.0,30.0,available,96.78,102.1,34.94,0.3422
2024-01-21 23:59:00,96.05,0.0,0.0,off,30.0,available,96.05,0.0,0.0,off,...,0.0,0.0,off,0.0,30.0,available,96.05,96.9,35.68,0.3682

In [4]:
data_quality_checks_results = data_quality_checks(df, DATA_SPECIFICATION)

In [7]:
rs = calculate_specific_power_windows(df, COMPRESSOR_SPECS)
rs

{'compressor_1': {'spec_specific_power': 0.24444444444444444,
  'windowed': [{'window': '2024-01-15 00:00',
    'is_loaded': 675,
    'actual_specific_power': 0.28611386139950906,
    'flow': 210.8282638888889,
    'power': 62.82888888888889,
    'above_spec': 675},
   {'window': '2024-01-16 00:00',
    'is_loaded': 680,
    'actual_specific_power': 0.28612563740076496,
    'flow': 212.34055555555557,
    'power': 63.16195833333333,
    'above_spec': 680},
   {'window': '2024-01-17 00:00',
    'is_loaded': 668,
    'actual_specific_power': 0.2859812386439086,
    'flow': 208.746875,
    'power': 62.302770833333334,
    'above_spec': 668},
   {'window': '2024-01-18 00:00',
    'is_loaded': 663,
    'actual_specific_power': 0.2863584493198077,
    'flow': 207.09243055555555,
    'power': 61.99747222222222,
    'above_spec': 663},
   {'window': '2024-01-19 00:00',
    'is_loaded': 658,
    'actual_specific_power': 0.28591100510229767,
    'flow': 205.76506944444446,
    'power': 61.59122222222222,
    'above_spec': 658},
   {'window': '2024-01-20 00:00',
    'is_loaded': 265,
    'actual_specific_power': 0.2866735964038822,
    'flow': 82.80847222222222,
    'power': 24.26474305555556,
    'above_spec': 265},
   {'window': '2024-01-21 00:00',
    'is_loaded': 224,
    'actual_specific_power': 0.28615644567364956,
    'flow': 70.09416666666667,
    'power': 21.211416666666665,
    'above_spec': 224}]},
 'compressor_2': {'spec_specific_power': 0.24444444444444444,
  'windowed': [{'window': '2024-01-15 00:00',
    'is_loaded': 811,
    'actual_specific_power': 0.2447948877261037,
    'flow': 253.26375,
    'power': 64.25899305555555,
    'above_spec': 403},
   {'window': '2024-01-16 00:00',
    'is_loaded': 714,
    'actual_specific_power': 0.24551042112312513,
    'flow': 222.814375,
    'power': 57.888423611111115,
    'above_spec': 413},
   {'window': '2024-01-17 00:00',
    'is_loaded': 716,
    'actual_specific_power': 0.2454440355913695,
    'flow': 223.3346527777778,
    'power': 57.99655555555555,
    'above_spec': 396},
   {'window': '2024-01-18 00:00',
    'is_loaded': 787,
    'actual_specific_power': 0.2446023664085189,
    'flow': 245.87583333333333,
    'power': 62.77155555555555,
    'above_spec': 410},
   {'window': '2024-01-19 00:00',
    'is_loaded': 713,
    'actual_specific_power': 0.24511552005928253,
    'flow': 222.85729166666667,
    'power': 57.77320138888889,
    'above_spec': 372},
   {'window': '2024-01-20 00:00',
    'is_loaded': 490,
    'actual_specific_power': 0.24448596885668847,
    'flow': 153.293125,
    'power': 39.15128472222222,
    'above_spec': 243},
   {'window': '2024-01-21 00:00',
    'is_loaded': 468,
    'actual_specific_power': 0.24547440802315404,
    'flow': 145.99756944444445,
    'power': 37.26768055555556,
    'above_spec': 262}]},
 'compressor_3': {'spec_specific_power': 0.23684210526315788,
  'windowed': [{'window': '2024-01-15 00:00',
    'is_loaded': 1440,
    'actual_specific_power': 0.2771678851053623,
    'flow': 236.73069444444445,
    'power': 61.73798611111111,
    'above_spec': 1352},
   {'window': '2024-01-16 00:00',
    'is_loaded': 1440,
    'actual_specific_power': 0.27689426581440074,
    'flow': 236.29631944444446,
    'power': 61.6118125,
    'above_spec': 1348},
   {'window': '2024-01-17 00:00',
    'is_loaded': 1440,
    'actual_specific_power': 0.27716235986055426,
    'flow': 235.62888888888887,
    'power': 61.52253472222222,
    'above_spec': 1343},
   {'window': '2024-01-18 00:00',
    'is_loaded': 1440,
    'actual_specific_power': 0.2762028891600448,
    'flow': 236.6346527777778,
    'power': 61.67420833333333,
    'above_spec': 1355},
   {'window': '2024-01-19 00:00',
    'is_loaded': 1440,
    'actual_specific_power': 0.2772820246121671,
    'flow': 236.14916666666664,
    'power': 61.65385416666667,
    'above_spec': 1355},
   {'window': '2024-01-20 00:00',
    'is_loaded': 1440,
    'actual_specific_power': 0.3055741807751476,
    'flow': 157.29118055555554,
    'power': 46.07165972222222,
    'above_spec': 1440},
   {'window': '2024-01-21 00:00',
    'is_loaded': 1440,
    'actual_specific_power': 0.3035585542765112,
    'flow': 159.09298611111112,
    'power': 46.35317361111112,
    'above_spec': 1440}]},
 'compressor_4': {'spec_specific_power': 0.25,
  'windowed': [{'window': '2024-01-15 00:00',
    'is_loaded': 960,
    'actual_specific_power': 0.29760525436146573,
    'flow': 270.34944444444443,
    'power': 78.50502083333333,
    'above_spec': 959},
   {'window': '2024-01-16 00:00',
    'is_loaded': 960,
    'actual_specific_power': 0.2974895794827107,
    'flow': 270.18340277777776,
    'power': 78.32353472222222,
    'above_spec': 959},
   {'window': '2024-01-17 00:00',
    'is_loaded': 960,
    'actual_specific_power': 0.29716976293276964,
    'flow': 269.55229166666663,
    'power': 78.14811805555556,
    'above_spec': 954},
   {'window': '2024-01-18 00:00',
    'is_loaded': 960,
    'actual_specific_power': 0.2977203563438598,
    'flow': 270.3333333333333,
    'power': 78.42520138888888,
    'above_spec': 955},
   {'window': '2024-01-19 00:00',
    'is_loaded': 960,
    'actual_specific_power': 0.29784965757167553,
    'flow': 269.90020833333335,
    'power': 78.42140277777779,
    'above_spec': 956},
   {'window': '2024-01-20 00:00',
    'is_loaded': 0,
    'actual_specific_power': nan,
    'flow': 0.0,
    'power': 0.0,
    'above_spec': 0},
   {'window': '2024-01-21 00:00',
    'is_loaded': 0,
    'actual_specific_power': nan,
    'flow': 0.0,
    'power': 0.0,
    'above_spec': 0}]}}

In [23]:
rs['compressor_1']['windowed']

,window,is_loaded,actual_specific_power,flow,power,above_spec
0,2024-01-15,675,0.286114,210.828264,62.828889,675
1,2024-01-16,680,0.286126,212.340556,63.161958,680
2,2024-01-17,668,0.285981,208.746875,62.302771,668
3,2024-01-18,663,0.286358,207.092431,61.997472,663
4,2024-01-19,658,0.285911,205.765069,61.591222,658
5,2024-01-20,265,0.286674,82.808472,24.264743,265
6,2024-01-21,224,0.286156,70.094167,21.211417,224