In [2]:
import pandas as pd
import plotly.express as px

In [ ]:
sens = pd.read_csv("data/station_sensor_data.csv",parse_dates=["timestamp"])
sens['timestamp'] = sens['timestamp'].dt.round('min')
sens.head(10)

,timestamp,compressor_1_pressure,compressor_1_flow,compressor_1_power,compressor_1_activity,compressor_1_oil_temp,compressor_1_availability,compressor_2_pressure,compressor_2_flow,compressor_2_power,...,compressor_4_flow,compressor_4_power,compressor_4_activity,compressor_4_bov_position,compressor_4_oil_temp,compressor_4_availability,station_pressure,station_flow,station_power,station_specific_power
0,2024-01-15 00:00:00,96.07,0.0,0.0,off,30.0,available,96.07,0.0,0.0,...,0.0,0.0,off,0.0,30.0,available,96.07,119.4,37.56,0.3146
1,2024-01-15 00:00:54,96.27,0.0,0.0,off,30.0,available,96.27,0.0,0.0,...,0.0,0.0,off,0.0,30.0,available,96.27,113.4,34.19,0.3015
2,2024-01-15 00:02:17,96.66,0.0,0.0,off,30.0,available,96.66,0.0,0.0,...,0.0,0.0,off,0.0,30.0,available,96.66,102.1,34.82,0.3410
3,2024-01-15 00:02:49,96.13,0.0,0.0,off,30.0,available,96.13,0.0,0.0,...,0.0,0.0,off,0.0,30.0,available,96.13,110.6,34.54,0.3123
4,2024-01-15 00:03:49,95.73,0.0,0.0,off,30.0,available,95.73,0.0,0.0,...,0.0,0.0,off,0.0,30.0,available,95.73,117.3,36.86,0.3142
5,2024-01-15 00:04:43,96.33,0.0,0.0,off,30.0,available,96.33,0.0,0.0,...,0.0,0.0,off,0.0,30.0,available,96.33,113.5,36.59,0.3224
6,2024-01-15 00:06:16,96.01,0.0,0.0,off,30.0,available,96.01,0.0,0.0,...,0.0,0.0,off,0.0,30.0,available,96.01,113.6,39.35,0.3464
7,2024-01-15 00:06:54,96.12,0.0,0.0,off,30.0,available,96.12,0.0,0.0,...,0.0,0.0,off,0.0,30.0,available,96.12,112.7,38.31,0.3399
8,2024-01-15 00:07:46,95.45,0.0,0.0,off,30.0,available,95.45,0.0,0.0,...,0.0,0.0,off,0.0,30.0,available,95.45,106.5,33.96,0.3189
9,2024-01-15 00:08:48,96.00,0.0,0.0,off,30.0,available,96.00,0.0,0.0,...,0.0,0.0,off,0.0,30.0,available,96.00,102.1,34.71,0.3400

In [8]:
sens['timestamp'].dt.round('min')[:10]

0   2024-01-15 00:00:00
1   2024-01-15 00:01:00
2   2024-01-15 00:02:00
3   2024-01-15 00:03:00
4   2024-01-15 00:04:00
5   2024-01-15 00:05:00
6   2024-01-15 00:06:00
7   2024-01-15 00:07:00
8   2024-01-15 00:08:00
9   2024-01-15 00:09:00
Name: timestamp, dtype: datetime64[us]

In [10]:
sens['compressor_4_activity'].value_counts()

compressor_4_activity
off       5280
loaded    4800
Name: count, dtype: int64

In [4]:
sens.info()

<class 'pandas.DataFrame'>
RangeIndex: 10080 entries, 0 to 10079
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   timestamp                  10080 non-null  datetime64[us]
 1   compressor_1_pressure      10080 non-null  float64
 2   compressor_1_flow          10076 non-null  float64
 3   compressor_1_power         10076 non-null  float64
 4   compressor_1_activity      10080 non-null  str
 5   compressor_1_oil_temp      10080 non-null  float64
 6   compressor_1_availability  10080 non-null  str
 7   compressor_2_pressure      10080 non-null  float64
 8   compressor_2_flow          10080 non-null  float64
 9   compressor_2_power         10080 non-null  float64
 10  compressor_2_activity      10080 non-null  str
 11  compressor_2_oil_temp      10080 non-null  float64
 12  compressor_2_availability  10080 non-null  str
 13  compressor_3_pressure      10079 non-null  float64
 14  compressor_3_flow          10079 non-null  float64
 15  compressor_3_power         10079 non-null  float64
 16  compressor_3_activity      10080 non-null  str
 17  compressor_3_oil_temp      10079 non-null  float64
 18  compressor_3_availability  10080 non-null  str
 19  compressor_4_pressure      10080 non-null  float64
 20  compressor_4_flow          10080 non-null  float64
 21  compressor_4_power         10080 non-null  float64
 22  compressor_4_activity      10080 non-null  str
 23  compressor_4_bov_position  10080 non-null  float64
 24  compressor_4_oil_temp      10080 non-null  float64
 25  compressor_4_availability  10080 non-null  str
 26  station_pressure           10080 non-null  float64
 27  station_flow               10078 non-null  float64
 28  station_power              10078 non-null  float64
 29  station_specific_power     10078 non-null  float64
dtypes: datetime64[us](1), float64(21), str(8)
memory usage: 2.3 MB

In [17]:
fig = px.histogram(
    sens, 
    x=['compressor_1_flow', 'compressor_2_flow', 'compressor_3_flow', 'compressor_4_flow','station_flow'  ], 
    barmode='overlay', 
    opacity=0.6,
    nbins=40,
    title="Comparing Column Distributions (Wide Format)"
)

# Customizing axes labels
fig.update_layout(
    xaxis_title="Values",
    yaxis_title="Count",
    legend_title="Columns"
)
fig.show()

In [16]:
sens['specific_power_compressor_1'] = sens['compressor_1_power'] / sens['compressor_1_flow']
sens['specific_power_compressor_2'] = sens['compressor_2_power'] / sens['compressor_2_flow']
sens['specific_power_compressor_3'] = sens['compressor_3_power'] / sens['compressor_3_flow']        
sens['specific_power_compressor_4'] = sens['compressor_4_power'] / sens['compressor_4_flow']
fig = px.histogram(
    sens, 
    x=['specific_power_compressor_1', 'specific_power_compressor_2', 'specific_power_compressor_3', 'specific_power_compressor_4','station_specific_power'  ], 
    barmode='overlay', 
    opacity=0.6,
    nbins=50,
    title="Comparing Column Distributions (Wide Format)"
)
fig.show()

In [ ]:
sens['compressor_1_flow'].value_counts()

In [ ]:
specs = pd.read_json("data/compressor_specs.json", orient="")
specs

In [4]:
dat = pd.read_csv("data/data_specification.csv")
dat

,column_name,type,unit,normal_range,notes
0,timestamp,datetime,–,2024-01-15 00:00:00 to 2024-01-21 23:58:53,ISO 8601 format
1,compressor_1_pressure,float,PSI,98 – 103,Discharge pressure while loaded
2,compressor_1_flow,float,CFM,0 (off) / 422 – 475 (loaded),0 when off or unloaded
3,compressor_1_power,float,kW,0 (off) / 80 – 117 (loaded),0 when off or unloaded
4,compressor_1_activity,categorical,–,"off, unloaded, loaded",Operational state
5,compressor_1_oil_temp,float,°C,30 (cold) – 93 (running),Rises from 30°C at startup
6,compressor_1_availability,categorical,–,available,Asset availability status
7,compressor_2_pressure,float,PSI,98 – 103,Discharge pressure while loaded
8,compressor_2_flow,float,CFM,0 (off) / 417 – 477 (loaded),0 when off or unloaded
9,compressor_2_power,float,kW,0 (off) / 80 – 121 (loaded),0 when off or unloaded
10,compressor_2_activity,categorical,–,"off, unloaded, loaded",Operational state
11,compressor_2_oil_temp,float,°C,30 (cold) – 103 (running),Rises from 30°C at startup
12,compressor_2_availability,categorical,–,"available, in_maintenance",Asset availability status
13,compressor_3_pressure,float,PSI,106 – 110,Always loaded in this dataset
14,compressor_3_flow,float,CFM,56 – 374,Continuously running unit
15,compressor_3_power,float,kW,24 – 92,Continuously running unit
16,compressor_3_activity,categorical,–,loaded,Always loaded in this dataset
17,compressor_3_oil_temp,float,°C,31 – 92,Rises from 31°C at start of dataset
18,compressor_3_availability,categorical,–,available,Asset availability status
19,compressor_4_pressure,float,PSI,106 – 113,Discharge pressure while loaded
20,compressor_4_flow,float,CFM,0 (off) / 161 – 566 (loaded),0 when off
21,compressor_4_power,float,kW,0 (off) / 80 – 145 (loaded),0 when off
22,compressor_4_activity,categorical,–,"off, loaded",Operational state
23,compressor_4_bov_position,float,ratio,0.0 – 0.62,"Blow-off valve position (0 = closed, 1 = fully..."
24,compressor_4_oil_temp,float,°C,30 (cold) – 88 (running),Rises from 30°C at startup
25,compressor_4_availability,categorical,–,available,Asset availability status
26,station_pressure,float,PSI,90 – 120,Aggregate header pressure
27,station_flow,float,CFM,56 – 1791,Sum of all active compressor flows
28,station_power,float,kW,24 – 448,Sum of all active compressor power draws
29,station_specific_power,float,kW/CFM,0.235 – 0.556,Power per unit of air delivered; lower is bett...